services:
  softioc:
    image: jeffersonlab/softioc:1.1.0
    tty: true
    stdin_open: true
    hostname: softioc
    container_name: softioc
    volumes:
      - ./examples/softioc-db:/db
      - ./examples/softioc-scripts:/scripts

  epics2web:
    image: jeffersonlab/epics2web:1.14.1
    hostname: epics2web
    container_name: epics2web
    environment:
      EPICS_CA_ADDR_LIST: softioc
    ports:
      - 9090:8080
