services:
  softioc:
    extends:
      file: deps.yml
      service: softioc

  epics2web:
    extends:
      file: deps.yml
      service: epics2web

  wedm:
    hostname: wedm
    container_name: wedm
    environment:
      EDL_DIR: /edl
      EDMCOLORFILE: /edl/colors.list
      EPICS_2_WEB_HOST: localhost:9090
    depends_on:
      - epics2web
    ports:
      - 8080:8080
