name: DD
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - README.md
      - .github/workflows/dd.yml
jobs:
  description:
    uses: jeffersonlab/container-workflows/.github/workflows/docker-description.yml@v1
    secrets: inherit