name: Update DockerHub Description
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - README.md
      - .github/workflows/docker-description.yml
jobs:
  dockerHubDescription:
    uses: jeffersonlab/container-workflows/.github/workflows/docker-description.yml@main
    with:
      repository: jeffersonlab/${{ github.event.repository.name }}
      description: ${{ github.event.repository.description }}
    secrets: inherit