name: Release

on:
  push:
    paths:
      - 'VERSION'

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      semvertag: ${{ steps.getver.outputs.semvertag }}
    steps:
      - name: Dump github context
        run:   echo "$GITHUB_CONTEXT"
        shell: bash
        env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Build
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: wrapper
      - name: Build with Gradle
        run: ./gradlew build
      - name: Read version file
        id: getver
        run: |
          VER=$(cat VERSION)
          echo "VERSION=v$VER" >> $GITHUB_ENV
          echo "semvertag=v$VER" >> $GITHUB_OUTPUT
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          files: build/libs/wedm.war
          tag_name: ${{ env.VERSION }}

  docker_publish:
    needs:
      - release
    uses: jeffersonlab/wedm/.github/workflows/docker-publish.yml@main
    with:
      semvertag: ${{ needs.release.outputs.semvertag }}
    secrets: inherit